version: "3.9"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"                 # Дашборд без auth
      - "--api.dashboard=true"
      - "--providers.docker=true"             # Docker как провайдер
      - "--entrypoints.web.address=:8081"    # HTTP для сервисов
    ports:
      - "8081:8081"  # для фронтенда/бэкенда
      - "8080:8080"  # дашборд
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"
        - "traefik.http.routers.traefik.entrypoints=web"
        - "traefik.http.routers.traefik.service=api@internal"

  backend:
    image: project-backend:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`backend.local`)"
        - "traefik.http.routers.backend.entrypoints=web"
        - "traefik.http.services.backend.loadbalancer.server.port=8000"
    networks:
      - app-net
    environment:
      DATABASE_URL: postgresql+asyncpg://eums_user:eums_pass@postgres/eums
      REDIS_URL: redis://redis:6379/0

  frontend:
    image: project-frontend:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`frontend.local`)"
        - "traefik.http.routers.frontend.entrypoints=web"
        - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - app-net

  postgres:
    image: postgres:15
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_USER: eums_user
      POSTGRES_PASSWORD: eums_pass
      POSTGRES_DB: eums
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  redis:
    image: redis:7
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    driver: overlay
